python3 raft.py \
  --datapath data/RAFT.pdf \
  --output outputs \
  --output-format hf \ # or completion or chat
  --distractors 3 \
  --p 1.0 \
  --doctype pdf \
  --chunk_size 512 \
  --questions 2 \
  --system-prompt-key llama \
  --embedding_model doubao-embedding-large-text-250515 \
  --completion_model deepseek-r1-250120 \

# --embedding_model text-embedding-v2 \
# --completion_model qwen-plus \
# --openai_key f40416fd-bfd1-4370-b74f-15c3338d0c58
# --openai_key sk-f48122216ef34a308d4da05e4fa4c89a  ali apikey

python raft.py --datapath data/RAFT.pdf --output outputs --output-format hf --distractors 3 --p 1.0 --doctype pdf --chunk_size 512 --questions 2 --completion_model qwen-plus --openai_key sk-f48122216ef34a308d4da05e4fa4c89a
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test --output-format hf --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model qwen-plus --openai_key sk-f48122216ef34a308d4da05e4fa4c89a
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test01 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test02 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key llama
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test03 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 5 --completion_model deepseek-r1-250120 --system-prompt-key deepseek
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test04 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 5 --completion_model deepseek-r1-250120 --system-prompt-key deepseek
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test05 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 5 --completion_model deepseek-r1-250120 --system-prompt-key deepseek
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test06 --output-format completion --distractors 4 --p 1.0 --doctype txt --chunk_size 512 --questions 5 --completion_model deepseek-r1-250120 --system-prompt-key deepseek
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test07 --output-format completion --distractors 4 --p 1.0 --doctype txt --chunk_size 512 --questions 5 --completion_model deepseek-r1-250120 --system-prompt-key deepseek
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test08 --output-format completion --distractors 4 --p 1.0 --doctype txt --chunk_size 512 --questions 3 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“光电子学”课程的实践与思考_杨晓占_llm_correct.md --output outputs_test09 --output-format completion --distractors 4 --p 1.0 --doctype txt --chunk_size 512 --questions 5 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“半导体光电子学”双语教学探讨_贾宏志_llm_correct.md --output outputs_test10 --output-format completion --distractors 4 --p 1.0 --doctype txt --chunk_size 512 --questions 1 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“光电子学”课程的实践与思考_杨晓占_llm_correct.md --output outputs_test09 --output-format completion --distractors 4 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/97平板显示综述_朱昌昌_llm_correct.md --output outputs_test08 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“基于低温多晶硅TFT基板...ED关键技术研发”通过验收_llm_correct.md --output outputs_test11 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“战略性先进电子材料”重点...印刷TFT材料与器件的研究_张小涛_llm_correct.md --output outputs_test12 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“显示技术”网络课程的设计与开发_况亚伟_llm_correct.md --output outputs_test13 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“液晶显示器件物理专业方向”的实验设置_张志东_llm_correct.md --output outputs_test14 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“有机发光二极管（OLEDs）”专刊序_马於光_llm_correct.md --output outputs_test15 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“战略性先进电子材料”重点...印刷TFT材料与器件的研究_张小涛_llm_correct.md --output outputs_test16 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/“自发光”平板显示未雨绸缪...战LCD的SED、OLED_陈宏林_llm_correct.md --output outputs_test17 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/《OLED模组基本额定值和特性》国际提案要点解读_来航曼_llm_correct.md --output outputs_test18 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/《透明液晶显示光学测试方法》国际提案要点解读_来航曼_llm_correct.md --output outputs_test19 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/《显示器能效限定值及能效等级》标准解析_吴蔚华_llm_correct.md --output outputs_test20 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/■面InGaN量子阱中的静...光发光二极管光电性能的影响_尹瑞梅_llm_correct.md --output outputs_test21 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/1,8-萘酰亚胺类有机小分子电致发光材料的研究进展_王启_llm_correct.md --output outputs_test22 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/2.7”a-Si_TFT矩阵(英文)_熊绍珍_llm_correct.md --output outputs_test23 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/2-对联苯-8-羟基喹啉锌...及其应用于新型白光OLED_赵婷_llm_correct.md --output outputs_test24 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/2英寸全彩色AM-OLED显示屏的驱动方案_尹盛_llm_correct.md --output outputs_test25 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/3英寸黑白a-siTFT-LCD驱动系统_孙明峰_llm_correct.md --output outputs_test26 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/5G时代新型先进显示技术发...—访中国科学院院士欧阳钟灿_张莹_llm_correct.md --output outputs_test27 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/5种液晶显示优劣谈_llm_correct.md --output outputs_test28 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/6.5万彩色显示PM-OLED控制与驱动芯片_秦波_llm_correct.md --output outputs_test29 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/7.6cm多色有源矩阵液晶显示器_冯治兴_llm_correct.md --output outputs_test30 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/8光罩BCE结构IGZO-...的钝化层通孔柱状不良的改善_刘浩_llm_correct.md --output outputs_test31 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/9.5英寸对角线的多色非晶硅TFT-LCD板_陈宏琪_llm_correct.md --output outputs_test32 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/9款38cm(15英寸)TFT_LCD显示器横向评测_张韬_llm_correct.md --output outputs_test33 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/9英寸MIM矩阵式液晶显示器件_陈树民_llm_correct.md --output outputs_test34 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/10大新显示技术_llm_correct.md --output outputs_test35 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/10万象素a-Si_TFT有源矩阵的优化技术_徐重阳_llm_correct.md --output outputs_test36 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/12.7cm彩色AM-OLED显示屏的驱动模块_张繁_llm_correct.md --output outputs_test37 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/12.7cm彩色AM-OLED显示器分场驱动研究_沈亮_llm_correct.md --output outputs_test38 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/12.9英寸高分辨率多色TFT—LCD_师庆华_llm_correct.md --output outputs_test39 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/13.8英寸高分辨率多色TFT—LCD_王阳_llm_correct.md --output outputs_test40 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/17.8cm彩色AMOLED驱动模块的研制_尹盛_llm_correct.md --output outputs_test41 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/22cm反射式彩色TFT_LCD_孙再吉_llm_correct.md --output outputs_test42 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/22英寸广色域——HP_L2245w_真水无味_llm_correct.md --output outputs_test43 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/80C196KC与液晶显示...174的接口设计及编程实现_冯占英_llm_correct.md --output outputs_test44 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/125mm彩色AMOLED的多晶硅TFT基板_孟志国_llm_correct.md --output outputs_test45 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/128×64点阵式OLED的驱动电路_董桂芳_llm_correct.md --output outputs_test46 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/200mm×200mm_OLED步进投影曝光机_周畅_llm_correct.md --output outputs_test47 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/256×64点阵液晶显示器模块_吴训_llm_correct.md --output outputs_test48 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/256级灰度OLED驱动电路_陈志明_llm_correct.md --output outputs_test49 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/400×640象素液晶显示的研制_杨兆芳_llm_correct.md --output outputs_test50 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/640×480_TFT-AMLCD有源层的制备_葛长军_llm_correct.md --output outputs_test51 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/640×480像素矩阵OL...ilicon微显示芯片设计_陆超_llm_correct.md --output outputs_test52 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/980nm底发射VCSEL的DBR设计与优化_李特_llm_correct.md --output outputs_test53 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/1670万种色彩的15英寸TFT液晶显示_金锐_llm_correct.md --output outputs_test54 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/2005_OLED行业一瞥_王力_llm_correct.md --output outputs_test55 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Ⅱ-Ⅵ族化合物薄膜电致发光_钟国柱_llm_correct.md --output outputs_test56 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/A Method for OLED Test_llm_correct.md" --output outputs_test57 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/A new AC driv...ission AMOLED_张勇文_llm_correct.md" --output outputs_test58 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/A new OLED SP...isplay design_赵博华_llm_correct.md" --output outputs_test59 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/A physical ch...e a-IGZO TFTs_Minxi CAI_llm_correct.md" --output outputs_test60 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/A_purely_orga...ar-white_OLED_Jing Sun_llm_correct.md" --output outputs_test61 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AD9883在平板显示视频接口中的应用_胡建民_llm_correct.md --output outputs_test62 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ADS_TFT-LCD漏光敏感性影响因素研究与改善_冯伟_llm_correct.md --output outputs_test63 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ADS_TFT-LCD贴合产品按压漏光研究及改善_桂继维_llm_correct.md --output outputs_test64 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ADS模式TFT-LCD的显示原理研究_刘同海_llm_correct.md --output outputs_test65 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ADS双栅线结构高透像素设计_王小元_llm_correct.md --output outputs_test66 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ADS液晶面板划痕Mura研究_李晓吉_llm_correct.md --output outputs_test67 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Ag纳米线掺杂的液晶显示器件的电-光特性_赵东宇_llm_correct.md --output outputs_test68 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Ag阴极沉积速率对顶发射有机发光器件性能的影响_侯建华_llm_correct.md --output outputs_test69 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AIE材料助发光器件走出平面,迈向高维_孙景志_llm_correct.md --output outputs_test70 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-IGZO_IZO厚度比对TFT特性的影响研究_潘东_llm_correct.md --output outputs_test71 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AIT玻璃衬底非晶硅薄膜的固相晶化研究_郑文_llm_correct.md --output outputs_test72 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Al_2O_3_PMMA交...薄膜制备及OLED封装性能_周雄图_llm_correct.md --output outputs_test73 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Al_2O_3_SiN_X...___H__TFT_的研究_陈斌.md0000_llm_correct.md --output outputs_test74 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Al_2O_3薄层修饰Si...O-TFTs器件的性能研究_郭永林_llm_correct.md --output outputs_test75 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Al_2O_3沉积功率对共...n-O薄膜晶体管性能的影响_武明珠_llm_correct.md --output outputs_test76 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Al_Ti合金栅a-Si_TFT研究_熊绍珍_llm_correct.md --output outputs_test77 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AlGaInP_GaInP...OCVD外延片光学特性测试_王雅芳_llm_correct.md --output outputs_test78 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AlInGaN_GaN异质结构材料生长及特性研究_贾德宇_llm_correct.md --output outputs_test79 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Alq_3_HAT-CN叠...发光器件的激子调控机制探究_李万娇_llm_correct.md --output outputs_test80 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Alq_3光学特性研究的综合实验设计_杨凤_llm_correct.md --output outputs_test81 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Alq_3厚度以及沉积速率对OLED性能的影响_牟强_llm_correct.md --output outputs_test82 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Alq_3有机发光二极管中的超小磁场效应_张勇_llm_correct.md --output outputs_test83 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Alq_3有机发光二极管中的激子湮灭过程及其磁场效应_张勇_llm_correct.md --output outputs_test84 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Alq_3有机发光二极管中的正负磁电导转变_张勇_llm_correct.md --output outputs_test85 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Al栅a-Si_TFT栅绝缘膜研究_熊绍珍_llm_correct.md --output outputs_test86 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM_OLED_OLED的“明日之星”_王力_llm_correct.md --output outputs_test87 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM_OLED显示屏灰度驱动芯片电路的设计_冉峰_llm_correct.md --output outputs_test88 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AM－LCD用TFT有源矩阵的性能研究_张凤_llm_correct.md" --output outputs_test89 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AMOLED_TV产品与市场发展趋势_Kevin Liao_llm_correct.md" --output outputs_test90 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED_未来的软性显示技术_郑华琦_llm_correct.md --output outputs_test91 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AMOLED-TV更环保(英文)_Ken Werner_llm_correct.md" --output outputs_test92 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED不良MAP自动缺陷定位方法研究_曾建风_llm_correct.md --output outputs_test93 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED除泡工艺中智能搬送及分拣系统的设计与实现_田娜_llm_correct.md --output outputs_test94 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED大尺寸化面临的技术挑战_张斌_llm_correct.md --output outputs_test95 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED的图像缩放及时序控制方案_尹盛_llm_correct.md --output outputs_test96 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AM-OLED的像素电路集锦(二)_应根裕_llm_correct.md" --output outputs_test97 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AM-OLED的像素电路集锦(一)_应根裕_llm_correct.md" --output outputs_test98 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED电流镜像像素电路的稳定性分析_曹伟_llm_correct.md --output outputs_test99 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AMOLED电视功率管理解决方案_JT LEE_llm_correct.md" --output outputs_test100 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/AMOLED电视机商业化中的新兴技术_Hye Dong Kim_llm_correct.md" --output outputs_test101 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED灰阶补偿算法研究_张磊_llm_correct.md --output outputs_test102 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED技术发展现状及良率问题分析_魏亚东_llm_correct.md --output outputs_test103 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED技术领域全球专利布局分析_罗佳秀_llm_correct.md --output outputs_test104 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED技术专利申请分析_张曦_llm_correct.md --output outputs_test105 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED控制电路中内嵌I_2C控制核的研究与实现_郝大收_llm_correct.md --output outputs_test106 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED亮点不良修复方法_朱世楠_llm_correct.md --output outputs_test107 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED屏上驱动电路的设计_朱艳菊_llm_correct.md --output outputs_test108 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED驱动电路和LINUX下驱动程序设计_李国强_llm_correct.md --output outputs_test109 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED驱动管阈值的补偿方法综述_杨必文_llm_correct.md --output outputs_test110 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED驱动控制芯片的COB封装与测试_高艳丽_llm_correct.md --output outputs_test111 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED驱动控制芯片的测试电路设计_高艳丽_llm_correct.md --output outputs_test112 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED驱动控制芯片中电荷泵的设计_周静_llm_correct.md --output outputs_test113 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED驱动芯片内置SRAM控制方法研究_汪宏志_llm_correct.md --output outputs_test114 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED头盔显示器光学系统设计及视空间评价_范海英_llm_correct.md --output outputs_test115 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED微型显示器在红外系统中的应用_李延东_llm_correct.md --output outputs_test116 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED显示屏驱动芯片...emura数据的烧录与读取_杨国忠_llm_correct.md --output outputs_test117 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED显示屏驱动芯片...IPI-DSI的研究与实现_张洁_llm_correct.md --output outputs_test118 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED显示器件夜视兼容特性分析_赵小珍_llm_correct.md --output outputs_test119 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED像素电路的设计与仿真研究_沈匿_llm_correct.md --output outputs_test120 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED像素驱动电路的研究_李震梅_llm_correct.md --output outputs_test121 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AM-OLED像素驱动电路的研究_杨佳_llm_correct.md --output outputs_test122 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED像素驱动电路及其驱动系统_周志伟_llm_correct.md --output outputs_test123 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED制备关键技术研究_吕琳_llm_correct.md --output outputs_test124 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AMOLED子像素渲染算法研究_徐京_llm_correct.md --output outputs_test125 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/An integrated...Ts for AMOLED_赵丽晴_llm_correct.md" --output outputs_test126 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AOI检测技术应用及在印刷式OLED发展方向_许剑_llm_correct.md --output outputs_test127 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ArF准分子激光晶化非晶硅薄膜微结构研究_黄香平_llm_correct.md --output outputs_test128 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ARM7全彩OLED驱动控制电路设计_张翔_llm_correct.md --output outputs_test129 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ARM9芯片EP9315驱动TFT-LCD的研究_张恒_llm_correct.md --output outputs_test130 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ARM芯片S3C2410驱动TFT-LCD的研究_张义磊_llm_correct.md --output outputs_test131 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ArrayTFT基板Open类不良的研究_余舒娴_llm_correct.md --output outputs_test132 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/a－Si TFT LCD像素电压跃变效应及其补偿方法_张凤 _llm_correct.md" --output outputs_test133 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/a－Si TFT－LCD黑白视频投影显示_李树山_llm_correct.md" --output outputs_test134 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/a—Si TFT复合栅绝缘...极氧化Ta_2O_5的研究_熊绍珍_llm_correct.md" --output outputs_test135 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H_c-Si异质...V曲线的S-Shape现象_钟春良_llm_correct.md --output outputs_test136 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H_FLC光寻址液晶光阀性能研究_王江涛_llm_correct.md --output outputs_test137 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H_TFT电流-电压特性研究_万新恒_llm_correct.md --output outputs_test138 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H_TFT有源矩阵制造技术的研究_张少强_llm_correct.md --output outputs_test139 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H_TFT自对准工艺的研究_张少强_llm_correct.md --output outputs_test140 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H薄膜中Si_y..._x结构组态的原子模拟研究_翟世铭_llm_correct.md --output outputs_test141 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H基薄膜中SiH...单晶硅片钝化效果的影响研究_何玉平_llm_correct.md --output outputs_test142 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_H热处理过程中形成的纳米硅粒及其光致发光_薛清_llm_correct.md --output outputs_test143 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_TFT_LCD象素电压跳变特性研究_张盛东_llm_correct.md --output outputs_test144 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_TFT-LCD制...工艺中的ITO返修工艺研究_林鸿涛_llm_correct.md --output outputs_test145 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_TFT寻址LCD的动态特性_Miyata_llm_correct.md --output outputs_test146 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_TFT亚阈特征参数与有源层的厚度效应_宋跃_llm_correct.md --output outputs_test147 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si_TFT液晶显示模块的评价概述_闫亮_llm_correct.md --output outputs_test148 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si∶H_TFT亚阈值区SPICE模型的研究_邵喜斌_llm_correct.md --output outputs_test149 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si∶HTFT的寄生效应_宋跃_llm_correct.md --output outputs_test150 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si∶H-TFT阈值电...动OLED显示中的补偿设计_刘金娥_llm_correct.md --output outputs_test151 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-SiCdTe∶H薄膜做...晶光阀光敏层的光学特性研究_连雪艳_llm_correct.md --output outputs_test152 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-SiN_H薄膜的对靶溅射沉积及微结构特性研究_于威_llm_correct.md --output outputs_test153 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-SiN_x_H薄膜对a..._H_TFT阈值电压的影响_王长安_llm_correct.md --output outputs_test154 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/a－SiN∶H的退火处理及... TFT性能与可靠性的影响_李秀京_llm_correct.md" --output outputs_test155 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/a－SiTFT LCD象素电压跳变特性研究_张盛东_llm_correct.md" --output outputs_test156 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-SiTFT_PIN图像传感器件_赵颖_llm_correct.md --output outputs_test157 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-SiTFT有源矩阵的单故障交流导纳分析_宋跃_llm_correct.md --output outputs_test158 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-SiTFT中钼与非晶硅之间的互作用_赵颖_llm_correct.md --output outputs_test159 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/a-Si剩余膜厚对TFT特性的影响_田茂坤_llm_correct.md --output outputs_test160 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AV_TFT-LCD显示驱动的影响行为分析_张永栋_llm_correct.md --output outputs_test161 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/AZTO有源层厚度对薄膜晶体管性能的影响_胡小强_llm_correct.md --output outputs_test162 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/B_2O_3对LTPS用基板玻璃结构和黏温性能的影响_杨国洪_llm_correct.md --output outputs_test163 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/BCP的厚度对OLED性能的影响_王静_llm_correct.md --output outputs_test164 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/BePP_2沉积速率以及厚度对蓝光OLED性能的影响_安涛_llm_correct.md --output outputs_test165 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Bit-panel to ...e OLED matrix_llm_correct.md" --output outputs_test166 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Bphen掺杂Cs_2CO...层对OLED器件性能的影响_胡俊涛_llm_correct.md --output outputs_test167 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/B掺杂ZnO纳米薄膜的结构和光学特性研究_化麒麟_llm_correct.md --output outputs_test168 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/B样条曲面拟合在Mura缺陷获取中的应用_唐剑_llm_correct.md --output outputs_test169 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/C_(60)与MoO_3混...入层的单层有机电致发光器件_薛楷_llm_correct.md" --output outputs_test170 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/C51在液晶显示模块编程控制中的应用_张亚华_llm_correct.md --output outputs_test171 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/C545T对Al_MoO_...复合阳极OLED性能的影响_魏寅_llm_correct.md --output outputs_test172 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Calculation a...ency of OLEDs_llm_correct.md" --output outputs_test173 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Cat-CVD方法制备多晶硅薄膜的孕育层控制_张玉_llm_correct.md --output outputs_test174 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CCD彩色滤光片的制备与集成技术研究_黄建_llm_correct.md --output outputs_test175 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Cd_xZn_(1-x)O...的制备及非线性光学特性研究_张继德_llm_correct.md" --output outputs_test176 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CdSe_ZnS量子点下转...、绿、蓝顶发射有机发光器件_尹茂军_llm_correct.md --output outputs_test177 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CdSe薄膜晶体管制备工艺的研究_景玉梅_llm_correct.md --output outputs_test178 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CdS薄层对有机电致发光器件性能的影响_姜文龙_llm_correct.md --output outputs_test179 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CELL段OLED检测技术的现状及发展趋势_邱天_llm_correct.md --output outputs_test180 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Characteristi... for AM-OLEDs_张浩_llm_correct.md" --output outputs_test181 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CIE颜色匹配函数对LCD和OLED显示屏校准的影响_魏敏晨_llm_correct.md --output outputs_test182 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CM33-ZOC1007L...液晶材料HTNLCD的特性_梁兆颜_llm_correct.md --output outputs_test183 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CNT-FED点阵显示器件的研制及其驱动电路设计_戴丽娟_llm_correct.md --output outputs_test184 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Control of ep...sure in PECVD_沈艳娇_llm_correct.md" --output outputs_test185 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CPJ-1300偏光片除泡机的研制开发_刘军涛_llm_correct.md --output outputs_test186 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/CPLD控制液晶显示实验研究_吴浚浩_llm_correct.md --output outputs_test187 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Cs掺杂提高OLED效率与亮度的研究_林雯嫣_llm_correct.md --output outputs_test188 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/C掺杂GaAs外延层光学特性分析_邢艳辉_llm_correct.md --output outputs_test189 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DC3100：集成了DC-...C转换器的OLED驱动芯片_llm_correct.md --output outputs_test190 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Digital drive...OLED displays_llm_correct.md" --output outputs_test191 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DM642_Video_P...动TFT-LCD的改进方法_张超_llm_correct.md --output outputs_test192 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DOE在TFT特性探索中的应用_党亮英_llm_correct.md --output outputs_test193 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DPVBi空穴阻挡层对OLED性能的优化_廖亚琴_llm_correct.md --output outputs_test194 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DSP实现液晶显示图形的技术及应用_王小凤_llm_correct.md --output outputs_test195 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DSP与液晶显示器的接口和编程_王强_llm_correct.md --output outputs_test196 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Dual-Gate_TFT...D抖动算法FRC研究与实现_齐郾琴_llm_correct.md --output outputs_test197 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/DUV辅助高压退火对a-I...薄膜微结构及光学特性的影响_邹春晖_llm_correct.md --output outputs_test198 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ECR-PECVD方法低温制备多晶硅薄膜_冯庆浩_llm_correct.md --output outputs_test199 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Effects of or... OLED devices_胡俊涛_llm_correct.md" --output outputs_test200 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FED显示技术及其制作工艺探究_王惠_llm_correct.md --output outputs_test201 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FFS液晶显示模式下残像的非对称电压补偿研究_时成瑛_llm_correct.md --output outputs_test202 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FOLED薄膜封装技术研究进展_曾克俭_llm_correct.md --output outputs_test203 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FPGA的TFT-LCD真彩液晶屏显示控制_宋云霞_llm_correct.md --output outputs_test204 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FPGA实现的OLED视频处理系统_马静静_llm_correct.md --output outputs_test205 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FPGA实现全彩色OLED动态视频显示控制_金茂竹_llm_correct.md --output outputs_test206 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FreeRTOS在ZYNQ实时液晶显示系统中的应用_易文博_llm_correct.md --output outputs_test207 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/FTO上溅射ITO薄膜及光电性能_李亚玮_llm_correct.md --output outputs_test208 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/G2.5高分辨率TFT扫描投影曝光机_周畅_llm_correct.md --output outputs_test209 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/G6_AMOLED用宽幅钼平面溅射靶材的研制_单玉郎_llm_correct.md --output outputs_test210 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/GaN基TFT-LED有源阵列显示芯片的设计研究_杨利忠_llm_correct.md --output outputs_test211 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/GeSn材料的光电性质及其在薄膜晶体管的应用研究_张璐_llm_correct.md --output outputs_test212 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/GOA型TFT_LCD产品...sting工序烧伤现象研究_刘志军_llm_correct.md --output outputs_test213 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/H_2O_2对溶液法制备a...IGZO薄膜光学特性的影响_汤猛_llm_correct.md --output outputs_test214 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/H_2O_2氧化处理ZnO...道层对薄膜晶体管性能的影响_李博_llm_correct.md --output outputs_test215 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/H_2O对OLEDs寿命影响的探讨_沈吉明_llm_correct.md --output outputs_test216 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Halo_LDD_P-Si_TFT工艺参数优化_刘小红_llm_correct.md --output outputs_test217 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Halo_LDD多晶硅TFT载流子效应研究_吕志娟_llm_correct.md --output outputs_test218 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/High performa...ure oxide TFT_Rui Geng_llm_correct.md --output outputs_test219 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/H处理对a-Si_TFT矩阵性能的改善作用_赵颖_llm_correct.md --output outputs_test220 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/H扩散掺杂源漏的自对准顶栅...GZO_TFT制备工艺研究_付海时_llm_correct.md --output outputs_test221 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IBM制作出OLED用石墨烯透明电极_llm_correct.md --output outputs_test222 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ICP-MS测定TFT-L...D再生剥离液的金属元素探究_吴志平_llm_correct.md --output outputs_test223 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO_TFT详解_陶家顺_llm_correct.md --output outputs_test224 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO_TFT与ZnO_TFT的性能比较_吴为敬_llm_correct.md --output outputs_test225 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/IGZO-based ne...piking logics_Ying ZHU_llm_correct.md" --output outputs_test226 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO-TFT钝化层三元复合结构过孔刻蚀_田茂坤_llm_correct.md --output outputs_test227 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO-TFT技术_未来...寸平板显示应用发展的助推器_王莉红_llm_correct.md --output outputs_test228 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO薄膜溅射功率对IG...TFT栅电压不稳定性的影响_柳逢春_llm_correct.md --output outputs_test229 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO薄膜晶体管的制备及其光电性能_付钰_llm_correct.md --output outputs_test230 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IGZO型TFT图形设计优化_王国志_llm_correct.md --output outputs_test231 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IHS认为AMOLED的增长将成为显示屏行业的亮点_llm_correct.md --output outputs_test232 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/In_2O_3透明薄膜晶体管的制备及其电学性能的研究_徐天宁_llm_correct.md --output outputs_test233 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath "data/Influencing F... LTPS Process_王伟来_llm_correct.md" --output outputs_test234 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaN_GaN多量子阱...ED外延片的变温光致发光谱_杨超普_llm_correct.md --output outputs_test235 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaN_GaN多量子阱...N盖层的MOCVD生长研究_牛南辉_llm_correct.md --output outputs_test236 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaN_GaN微米阵列结构的生长及发光性能研究_张利繁_llm_correct.md --output outputs_test237 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaN量子点红光Micro-LED研究_余鹿鸣_llm_correct.md --output outputs_test238 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaZnO薄膜晶体管背...的层间Cu互连静电保护研究_马群刚_llm_correct.md --output outputs_test239 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaZnO薄膜晶体管背...极驱动电路静电释放失效研究_马群刚_llm_correct.md --output outputs_test240 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaZnO薄膜晶体管背板的栅极驱动电路静电释放失效研究-马群刚_llm_correct.md --output outputs_test241 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/InGaZnO薄膜晶体管泄漏电流模型_邓小庆_llm_correct.md --output outputs_test242 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IPS_TFT显示器用液晶材料的发展_沈吉明_llm_correct.md --output outputs_test243 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IPS-LCD大倾斜角离轴漏光补偿方法研究_张建军_llm_correct.md --output outputs_test244 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IPS模式液晶显示器件中COG_Mura的改善_尹刚_llm_correct.md --output outputs_test245 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/IPS液晶显示技术中国专利分析_吴永丽_llm_correct.md --output outputs_test246 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Ir配合物染料调节有机发光二极管发光特性_周思成_llm_correct.md --output outputs_test247 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ISA总线实现OLED面板显示_郑方_llm_correct.md --output outputs_test248 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/iSuppli_OLED电视2012年将达120万台_llm_correct.md --output outputs_test249 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO薄膜的近零介电常数波长的调控研究_周江昊_llm_correct.md --output outputs_test250 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO薄膜的制备、光刻及性能测试实验设计_张磊_llm_correct.md --output outputs_test251 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO薄膜性能、应用及其磁控溅射制备技术的研究_吴晓飞_llm_correct.md --output outputs_test252 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO表面改性对有机电致发光器件性能的影响_黎威志_llm_correct.md --output outputs_test253 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO导电玻璃及其在平板显示器中的应用_王士敏_llm_correct.md --output outputs_test254 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO退火工艺对HADS型TFT-LCD透过率的影响_安晖_llm_correct.md --output outputs_test255 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO像素电极工序对于HADS产品TFT特性的影响_林致远_llm_correct.md --output outputs_test256 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/ITO再生处理对有机电致发光器件特性的影响_林洋_llm_correct.md --output outputs_test257 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/L0周边Mura分析及其改善研究_王志龙_llm_correct.md --output outputs_test258 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/Langmuir探针对以S...积多晶硅薄膜过程的在线检测_祝祖送_llm_correct.md --output outputs_test259 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD、OELD、PDP三大平板显示技术新动向_钱志远_llm_correct.md --output outputs_test260 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD_Mura缺陷的B样条曲面拟合背景抑制_李坤_llm_correct.md --output outputs_test261 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD_OLED用紫外光固化胶粘剂研究进展_罗世永_llm_correct.md --output outputs_test262 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCDs用彩色滤光片_郭淑慈_llm_correct.md --output outputs_test263 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD彩色滤光片技术发展_李宏彦_llm_correct.md --output outputs_test264 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD的奥林匹克17英寸LCD显示器专题评测_吕华威_llm_correct.md --output outputs_test265 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD电视_OLED电视_...百科之影音基础知识普及之五_编辑部_llm_correct.md --output outputs_test266 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD和OLED平板电脑引...的视觉疲劳测量对比实验研究_陈成明_llm_correct.md --output outputs_test267 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD和TFT-LCD用玻璃基片_扈海燕_llm_correct.md --output outputs_test268 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD控制器驱动的24位TFT真彩屏接口设计_彭良智_llm_correct.md --output outputs_test269 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD面板TFT特性相关残像研究_许卓_llm_correct.md --output outputs_test270 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动电路的设计与实现_李晓飞_llm_correct.md --output outputs_test271 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动技术的最新进展_应根裕_llm_correct.md --output outputs_test272 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动控制时钟电路的设计_沃招军_llm_correct.md --output outputs_test273 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动器_孙再吉_llm_correct.md --output outputs_test274 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动器的新特性_钱金维_llm_correct.md --output outputs_test275 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动实时显示控制电路的Verilog设计_杨翠娥_llm_correct.md --output outputs_test276 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD驱动中调制算法的应用与实现研究_刘翼_llm_correct.md --output outputs_test277 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD显示屏HDR显示技术研究_曾少云_llm_correct.md --output outputs_test278 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD显示器的背光技术分析及应用_黄启智_llm_correct.md --output outputs_test279 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD显示器过驱动技术和运动内插技术的新进展_应根裕_llm_correct.md --output outputs_test280 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD显示器特性文件色域研究_洪亮_llm_correct.md --output outputs_test281 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/LCD液晶显示模块在工程装备计时系统中应用_袁建虎_llm_correct.md --output outputs_test282 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/640×480_TFTAMLCD有源层的制备_葛长军_llm_correct.md --output outputs_test283 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/640×480_TFTAMLCD有源层的制备_葛长军_llm_correct.md --output outputs_test284 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2
python raft.py --datapath data/640×480_TFTAMLCD有源层的制备_葛长军_llm_correct.md --output outputs_test285 --output-format completion --distractors 3 --p 1.0 --doctype txt --chunk_size 512 --questions 2 --completion_model deepseek-r1-250120 --system-prompt-key deepseek-v2

