python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks04.json" --questions_path "outputs_questions/article_questions04.json" --answers_path "outputs_answers/article_answers04.json" --syndatas_path "outputs_syndatas/syndatas05.json" --num_distract 4 --start_idx 9 --end_idx 11
python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks05.json" --questions_path "outputs_questions/article_questions05.json" --answers_path "outputs_answers/article_answers05.json" --syndatas_path "outputs_syndatas/syndatas06.json" --num_distract 4 --start_idx 9 --end_idx 11
python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks06.json" --questions_path "outputs_questions/article_questions06.json" --answers_path "outputs_answers/article_answers06.json" --syndatas_path "outputs_syndatas/syndatas07.json" --num_distract 4 --start_idx 11 --end_idx 15

python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks09.json" --embeddings_path "outputs_embeddings/chunk_embedding09.json" --questions_path "outputs_questions/article_questions09.json" --answers_path "outputs_answers/article_answers09.json" --syndatas_path "outputs_syndatas/syndatas09.json" --num_distract 4 --start_idx 15 --end_idx 18
python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks10.json" --embeddings_path "outputs_embeddings/chunk_embedding10.json" --questions_path "outputs_questions/article_questions10.json" --answers_path "outputs_answers/article_answers10.json" --syndatas_path "outputs_syndatas/syndatas10.json" --num_distract 4 --start_idx 18 --end_idx 21

python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks11.json" --embeddings_path "outputs_embeddings/chunk_embedding11.json" --questions_path "outputs_questions/article_questions11.json" --answers_path "outputs_answers/article_answers11.json" --syndatas_path "outputs_syndatas/syndatas11.json" --num_distract 4 --start_idx 21 --end_idx 24
python utils/syndata_pipeline.py --data_dir "data" --chunks_path "outputs_chunks/article_chunks12.json" --embeddings_path "outputs_embeddings/chunk_embedding12.json" --questions_path "outputs_questions/article_questions12.json" --answers_path "outputs_answers/article_answers12.json" --syndatas_path "outputs_syndatas/syndatas12.json" --num_distract 4 --start_idx 24 --end_idx 34

python -m utils.syndata_pipeline --data_dir "data" --chunks_path "outputs_chunks/article_chunks13.json" --embeddings_path "outputs_embeddings/chunk_embedding13.json" --questions_path "outputs_questions/article_questions13.json" --answers_path "outputs_answers/article_answers13.json" --syndatas_path "outputs_syndatas/syndatas13.json" --num_distract 4 --start_idx 34 --end_idx 36
